sudo: required
dist: trusty
language: cpp

services: 
  - docker
  
before_install:
  - docker pull dealii/dealii:v8.4.2-gcc-mpi-fulldepsmanual-release
  - docker run -t dealii/dealii:v8.4.2-gcc-mpi-fulldepsmanual-release /test_ci.sh
  

script: bash test_ci.sh
